import { PENDING, FULFILLED, REJECTED } from 'redux-promise-middleware';

const COMPUTE_PRICE = 'COMPUTE_PRICE';
const COMPUTE_PRICE_PENDING = `${COMPUTE_PRICE}_${PENDING}`;
const COMPUTE_PRICE_FULFILLED = `${COMPUTE_PRICE}_${FULFILLED}`;
const COMPUTE_PRICE_ERROR = `${COMPUTE_PRICE}_${REJECTED}`;

export default {
    COMPUTE_PRICE,
    COMPUTE_PRICE_PENDING,
    COMPUTE_PRICE_FULFILLED,
    COMPUTE_PRICE_ERROR,
};
